
POST  http://127.0.0.1:3000/usuarios
POST  http://127.0.0.1:3000/estoque
POST  http://127.0.0.1:3000/vendas

Content-type: application/json
# Content-type: application/json, avisa que o corpo da requisição está no formato JSON
